version: '3'

networks:
  my-kafka-network:
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    restart: always
    networks:
      - my-kafka-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_PORT=2181
    ports:
      - '2181:2181'

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    networks:
      - my-kafka-network
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=LISTENER_INNER://kafka:29092,LISTENER_OUTDOOR://kafka:9092
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_INNER://kafka:29092,LISTENER_OUTDOOR://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_INNER:PLAINTEXT,LISTENER_OUTDOOR:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_INNER
    ports:
      - '9092:9092'
      - '29092:29092'

  producer:
    build: ./producer
    depends_on:
      - kafka
    restart: always
    networks:
      - my-kafka-network
    ports:
      - "8080:8080"

  consumer:
    build: ./consumer
    depends_on:
      - kafka
    restart: always
    networks:
      - my-kafka-network
    ports:
      - "8081:8081"